[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Connie Hilarides <conni_h@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itoa = "0.4.4"
pathfinding = "2.0.0"
permutator = "0.3.3"
